# Generated by Django 6.0.3 on 2026-07-03 21:34

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0003_material_input_types'),
        ('plans', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tool_type', models.CharField(choices=[('line', 'Line')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, help_text='Leave blank for a global assembly available to every account.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_assemblies', to='accounts.account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CalculationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='e.g. "Stud", "Top Plate", "Bottom Plate" — shown on the BOM.', max_length=100)),
                ('formula_kind', models.CharField(choices=[('per_spacing', 'Count by spacing (e.g. studs)'), ('per_stock_length', 'Count by stock length (e.g. plates)')], max_length=20)),
                ('multiplier', models.PositiveSmallIntegerField(default=1, help_text='PER_STOCK_LENGTH: e.g. 2 for a double top plate.')),
                ('extra', models.IntegerField(default=0, help_text='PER_SPACING: e.g. +1 for the end stud.')),
                ('waste_factor', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=4)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='estimating.assembly')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculation_rules', to='catalog.materialproduct')),
            ],
            options={
                'ordering': ['assembly', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100)),
                ('length_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('waste_factor', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=4)),
                ('source', models.CharField(choices=[('tool', 'Tool'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calculation_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='estimating.calculationrule')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='projects.estimate')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='catalog.materialproduct')),
                ('trace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='plans.trace')),
            ],
            options={
                'ordering': ['role', 'material__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='assembly',
            constraint=models.UniqueConstraint(condition=models.Q(('account__isnull', True)), fields=('tool_type', 'name'), name='unique_global_assembly_name_per_tool_type'),
        ),
        migrations.AddConstraint(
            model_name='assembly',
            constraint=models.UniqueConstraint(condition=models.Q(('account__isnull', False)), fields=('account', 'tool_type', 'name'), name='unique_account_assembly_name_per_tool_type'),
        ),
    ]
