# Generated by Django 6.0.3 on 2026-07-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimating', '0002_seed_wall_assembly'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationrule',
            name='coverage_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='PER_AREA_COVERAGE: square feet one unit covers, e.g. 32 for a 4x8 sheet.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='tool_type',
            field=models.CharField(choices=[('line', 'Line (Wall)'), ('area', 'Area (Floor / Roof / Sheathing)'), ('count', 'Count (Posts / Hardware)'), ('opening', 'Opening (Window / Door)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='calculationrule',
            name='extra',
            field=models.IntegerField(default=0, help_text='PER_SPACING / PER_AREA_SPACING: e.g. +1 for the end member.'),
        ),
        migrations.AlterField(
            model_name='calculationrule',
            name='formula_kind',
            field=models.CharField(choices=[('per_spacing', 'Count by spacing along a line (e.g. studs)'), ('per_stock_length', 'Count by stock length along a run (e.g. plates, rim board)'), ('per_length', 'Piece(s) cut to the traced length (e.g. a beam)'), ('per_area_spacing', 'Members across an area by spacing (e.g. joists, rafters, trusses)'), ('per_area_coverage', 'Units by coverage area (e.g. sheathing sheets, felt rolls)'), ('per_count', 'Per counted point (e.g. posts, hangers)'), ('header', 'Header sized to the opening width'), ('fixed_count', 'Fixed count per trace (e.g. king studs, trimmers)')], max_length=20),
        ),
    ]
