# Generated by Django 6.0.3 on 2026-07-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimating', '0004_seed_house_assemblies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationrule',
            name='role',
            field=models.CharField(help_text='e.g. "Stud", "Top Plate", "Bottom Plate" - shown on the BOM.', max_length=100),
        ),
    ]
