# Generated by Django 6.0.3 on 2026-07-04 13:23

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('estimating', '0005_alter_calculationrule_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationrule',
            name='formula_kind',
            field=models.CharField(blank=True, choices=[('per_spacing', 'Count by spacing along a line (e.g. studs)'), ('per_stock_length', 'Count by stock length along a run (e.g. plates, rim board)'), ('per_length', 'Piece(s) cut to the traced length (e.g. a beam)'), ('per_area_spacing', 'Members across an area by spacing (e.g. joists, rafters, trusses)'), ('per_area_coverage', 'Units by coverage area (e.g. sheathing sheets, felt rolls)'), ('per_count', 'Per counted point (e.g. posts, hangers)'), ('header', 'Header sized to the opening width'), ('fixed_count', 'Fixed count per trace (e.g. king studs, trimmers)')], max_length=20),
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('measurement_kind', models.CharField(choices=[('line_lf', 'Line length (LF)'), ('area_sqft', 'Area (SF)'), ('perimeter_lf', 'Perimeter (LF)'), ('count', 'Count')], max_length=20)),
                ('multiplier', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10)),
                ('addend', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, help_text='Leave blank for a stock formula available to every account.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_formulas', to='accounts.account')),
                ('base_formula', models.ForeignKey(blank=True, help_text='Optional formula to build on. Account formulas can derive from stock formulas.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_formulas', to='estimating.formula')),
            ],
            options={
                'ordering': ['measurement_kind', 'name'],
            },
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='formula',
            field=models.ForeignKey(blank=True, help_text='Reusable library formula. Leave blank to use a framing formula kind.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculation_rules', to='estimating.formula'),
        ),
        migrations.AddConstraint(
            model_name='formula',
            constraint=models.UniqueConstraint(condition=models.Q(('account__isnull', True)), fields=('name',), name='unique_global_formula_name'),
        ),
        migrations.AddConstraint(
            model_name='formula',
            constraint=models.UniqueConstraint(condition=models.Q(('account__isnull', False)), fields=('account', 'name'), name='unique_account_formula_name'),
        ),
    ]
