# Generated by Django 6.0.3 on 2026-07-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimating', '0007_seed_stock_formulas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='tool_type',
            field=models.CharField(choices=[('line', 'Line (Wall)'), ('polyline', 'Polyline / Polygon'), ('area', 'Area (Floor / Roof / Sheathing)'), ('count', 'Count (Posts / Hardware)'), ('opening', 'Opening (Window / Door)')], max_length=20),
        ),
    ]
