# Generated by Django 6.0.3 on 2026-07-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimating', '0008_alter_assembly_tool_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationrule',
            name='units_per_measurement',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='PER_BOX: estimated units of the material (e.g. fasteners) consumed per foot/sqft/count of the trace measurement - a starting estimate to tune to your own practice, not an engineered fastener schedule.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calculationrule',
            name='formula_kind',
            field=models.CharField(blank=True, choices=[('per_spacing', 'Count by spacing along a line (e.g. studs)'), ('per_stock_length', 'Count by stock length along a run (e.g. plates, rim board)'), ('per_length', 'Piece(s) cut to the traced length (e.g. a beam)'), ('per_area_spacing', 'Members across an area by spacing (e.g. joists, rafters, trusses)'), ('per_area_coverage', 'Units by coverage area (e.g. sheathing sheets, felt rolls)'), ('per_count', 'Per counted point (e.g. posts, hangers)'), ('header', 'Header sized to the opening width'), ('fixed_count', 'Fixed count per trace (e.g. king studs, trimmers)'), ('per_box', 'Boxes from an estimated per-unit rate (e.g. fasteners)')], max_length=20),
        ),
    ]
