# Generated by Django 6.0.3 on 2026-07-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimating', '0010_fix_rafters_and_seed_fasteners'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='category',
            field=models.CharField(choices=[('foundation_sill', 'Foundation & Sill'), ('floor_system', 'Floor System'), ('wall_system', 'Wall System'), ('openings', 'Openings'), ('stairs', 'Stairs'), ('ceiling', 'Ceiling'), ('roof', 'Roof'), ('siding_exterior', 'Siding & Exterior Trim'), ('exterior_deck', 'Exterior Deck'), ('misc', 'Miscellaneous')], default='misc', help_text='Construction system this assembly belongs to, for grouping the material list.', max_length=20),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='category',
            field=models.CharField(choices=[('foundation_sill', 'Foundation & Sill'), ('floor_system', 'Floor System'), ('wall_system', 'Wall System'), ('openings', 'Openings'), ('stairs', 'Stairs'), ('ceiling', 'Ceiling'), ('roof', 'Roof'), ('siding_exterior', 'Siding & Exterior Trim'), ('exterior_deck', 'Exterior Deck'), ('misc', 'Miscellaneous')], default='misc', help_text='Construction system for grouping the material list. Set from the assembly at generation time for tool-sourced lines; chosen directly for manual ones. Denormalized rather than derived live, since calculation_rule is nullable (SET_NULL) and manual lines have no rule/assembly at all - read via Coalesce(calculation_rule__assembly__category, category) wherever grouping/order needs to reflect a later assembly edit.', max_length=20),
        ),
    ]
