# Generated by Django 6.0.3 on 2026-07-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimating', '0012_backfill_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationrule',
            name='corner_stud_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='PER_SPACING: extra studs added per corner OCCURRENCE this wall participates in - its own polyline bend (counted twice, matching two separate walls meeting end-to-end) or meeting another wall end-to-end (counted once) - a starting estimate, tune to your framing convention.'),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='t_backer_stud_count',
            field=models.PositiveSmallIntegerField(default=1, help_text="PER_SPACING: extra backer/nailer studs where ANOTHER wall's end butts into THIS wall's span (the through-wall side of a T-intersection)."),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='t_intersection_stud_count',
            field=models.PositiveSmallIntegerField(default=1, help_text="PER_SPACING: extra studs where THIS wall's end butts into another wall's span (the partition side of a T-intersection)."),
        ),
    ]
