# Generated by Django 6.0.3 on 2026-07-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_layout_preferences'),
        ('estimating', '0013_add_junction_stud_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='beam_type',
            field=models.CharField(blank=True, choices=[('flush', 'Flush'), ('dropped', 'Dropped')], help_text='Flush (within floor/ceiling depth) or dropped (hangs below) - classification only for now.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='opening_kind',
            field=models.CharField(blank=True, choices=[('window', 'Window'), ('door', 'Door')], help_text='OPENING assemblies only: window or door, matched against the attached Trace.settings.opening_type.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='wall_subtype',
            field=models.CharField(blank=True, choices=[('exterior', 'Exterior'), ('interior_bearing', 'Interior Bearing'), ('interior_non_bearing', 'Interior Non-Bearing')], help_text="Dual-purpose: for a WALL assembly (tool_type line/polyline), the wall type it represents. For an OPENING assembly (tool_type opening), the wall type its header/king/jack sizing is designed for - matched against the host wall Trace.parent_wall points to, so a window/door's materials can be auto-resolved from whichever wall it gets attached to.", max_length=25, null=True),
        ),
        migrations.AddConstraint(
            model_name='assembly',
            constraint=models.UniqueConstraint(condition=models.Q(('account__isnull', True), ('opening_kind__isnull', False), ('wall_subtype__isnull', False)), fields=('opening_kind', 'wall_subtype'), name='unique_global_opening_kind_wall_subtype'),
        ),
        migrations.AddConstraint(
            model_name='assembly',
            constraint=models.UniqueConstraint(condition=models.Q(('account__isnull', False), ('opening_kind__isnull', False), ('wall_subtype__isnull', False)), fields=('account', 'opening_kind', 'wall_subtype'), name='unique_account_opening_kind_wall_subtype'),
        ),
    ]
