# Generated by Django 6.0.3 on 2026-07-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimating', '0018_seed_siding_and_spliced_assemblies'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Auto-selected in the plan viewer when its tool/variant is picked, so drawing produces a material list without opening the assembly dropdown. Seed at most one default per tool-variant group (e.g. one exterior-wall default).'),
        ),
    ]
