# Generated by Django 6.0.3 on 2026-07-09 21:40

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_LOAD_TYPES = [
    'Basement Wall System',
    'Basement Floor System',
    'First Floor System',
    'First Floor Wall System',
    'Second Floor System',
    'Second Floor Wall System',
    'Third Floor System',
    'Third Floor Wall System',
    'Roof System',
    'Siding & Trim',
    'Interior Trim',
    'Miscellaneous',
]


def seed_load_types(apps, schema_editor):
    LoadType = apps.get_model('estimating', 'LoadType')
    for index, name in enumerate(DEFAULT_LOAD_TYPES, start=1):
        LoadType.objects.get_or_create(
            account_id=None,
            name=name,
            defaults={'display_order': index},
        )


def unseed_load_types(apps, schema_editor):
    LoadType = apps.get_model('estimating', 'LoadType')
    LoadType.objects.filter(account_id__isnull=True, name__in=DEFAULT_LOAD_TYPES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_layout_preferences'),
        ('estimating', '0021_material_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('account', models.ForeignKey(blank=True, help_text='Leave blank for a global load type available to every account.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_load_types', to='accounts.account')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='lineitem',
            name='load_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='estimating.loadtype'),
        ),
        migrations.AddConstraint(
            model_name='loadtype',
            constraint=models.UniqueConstraint(condition=models.Q(('account__isnull', True)), fields=('name',), name='unique_global_load_type_name'),
        ),
        migrations.AddConstraint(
            model_name='loadtype',
            constraint=models.UniqueConstraint(condition=models.Q(('account__isnull', False)), fields=('account', 'name'), name='unique_account_load_type_name'),
        ),
        migrations.RunPython(seed_load_types, unseed_load_types),
    ]
