# Generated by Django 6.0.3 on 2026-07-09 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_materialprice'),
        ('estimating', '0022_loadtype_lineitem_load_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationrule',
            name='preferred_length',
            field=models.ForeignKey(blank=True, help_text='Pin this rule to always use this exact stock length, regardless of the measured run. Leave blank to auto-resolve at calculation time (smallest length that fits / material default / spliced from the longest length).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_rules', to='catalog.materiallength'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='stock_length',
            field=models.ForeignKey(blank=True, help_text='The specific catalog stock length used for this line (FT materials only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='catalog.materiallength'),
        ),
    ]
