# Generated by Django 6.0.3 on 2026-07-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the user confirmed this address via the emailed link. Signing in never requires it; Stripe checkout does.', null=True),
        ),
    ]
