# Generated by Django 6.0.3 on 2026-07-03 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_floors', models.PositiveSmallIntegerField(default=1)),
                ('has_basement', models.BooleanField(default=False)),
                ('basement_wall_height_in', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('first_floor_wall_height_in', models.PositiveSmallIntegerField(default=108)),
                ('second_floor_wall_height_in', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stud_spacing_in', models.PositiveSmallIntegerField(choices=[(16, '16" OC'), (24, '24" OC')], default=16)),
                ('roof_framing', models.CharField(choices=[('rafters', 'Rafters'), ('trusses', 'Trusses'), ('both', 'Both')], default='trusses', max_length=20)),
                ('floor_material', models.CharField(blank=True, max_length=255)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_settings', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Estimate 1', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
