# Generated by Django 6.0.3 on 2026-07-04 18:32

from django.db import migrations, models


def backfill_foundation_type(apps, schema_editor):
    """Replaces the old has_basement boolean, which couldn't distinguish a
    crawl space (still needs floor framing) from a slab (doesn't). Existing
    True/False values only tell us basement-or-not, so they map to the two
    closest new values; anyone actually on a crawl space needs to re-pick it
    once via the Job Settings page."""
    JobSettings = apps.get_model('projects', 'JobSettings')
    JobSettings.objects.filter(has_basement=True).update(foundation_type='full_basement')
    JobSettings.objects.filter(has_basement=False).update(foundation_type='slab')


def undo_backfill(apps, schema_editor):
    JobSettings = apps.get_model('projects', 'JobSettings')
    JobSettings.objects.filter(foundation_type='full_basement').update(has_basement=True)
    JobSettings.objects.filter(foundation_type__in=['slab', 'crawl_space']).update(has_basement=False)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsettings',
            name='foundation_type',
            field=models.CharField(choices=[('slab', 'Slab on grade'), ('crawl_space', 'Crawl space'), ('full_basement', 'Full basement')], default='slab', help_text='A slab has no floor framing; a crawl space or full basement does.', max_length=20),
        ),
        migrations.RunPython(backfill_foundation_type, undo_backfill),
        migrations.RemoveField(
            model_name='jobsettings',
            name='has_basement',
        ),
    ]
