# Generated by Django 6.0.3 on 2026-07-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_foundation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsettings',
            name='roof_pitch_rise_per_12',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rise in inches per 12" of run, e.g. 6 for a 6/12 pitch. Leave blank if not yet known.', null=True),
        ),
        migrations.AddField(
            model_name='jobsettings',
            name='siding_material',
            field=models.CharField(blank=True, help_text='E.g. "Vinyl siding", "Hardie board", "Brick veneer".', max_length=255),
        ),
    ]
