# Generated by Django 6.0.3 on 2026-07-03 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0003_material_input_types'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='plans/source/%Y/%m/')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='projects.project')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='plans/pages/%Y/%m/')),
                ('thumbnail', models.ImageField(upload_to='plans/thumbnails/%Y/%m/')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='plans.plan')),
            ],
            options={
                'ordering': ['plan', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='ToolPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tool_type', models.CharField(choices=[('line', 'Line')], max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_presets', to='accounts.account')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_presets', to='catalog.materialproduct')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(choices=[('line', 'Line')], max_length=20)),
                ('geometry', models.JSONField()),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traces', to='catalog.materialproduct')),
                ('plan_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='plans.planpage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='planpage',
            constraint=models.UniqueConstraint(fields=('plan', 'page_number'), name='unique_plan_page_number'),
        ),
        migrations.AddConstraint(
            model_name='toolpreset',
            constraint=models.UniqueConstraint(fields=('account', 'tool_type', 'name'), name='unique_preset_name_per_account_tool'),
        ),
    ]
