# Generated by Django 6.0.3 on 2026-07-03 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimating', '0002_seed_wall_assembly'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpage',
            name='scale_pixels_per_foot',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Set by the Calibrate tool. Null means this page has not been calibrated yet.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trace',
            name='assembly',
            field=models.ForeignKey(blank=True, help_text='When set, the calculation engine generates LineItems from this Trace.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traces', to='estimating.assembly'),
        ),
    ]
