# Generated by Django 6.0.3 on 2026-07-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_planpage_scale_pixels_per_foot_trace_assembly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolpreset',
            name='tool_type',
            field=models.CharField(choices=[('line', 'Line (Wall)'), ('area', 'Area (Floor / Roof / Sheathing)'), ('count', 'Count (Posts / Hardware)'), ('opening', 'Opening (Window / Door)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trace',
            name='tool_type',
            field=models.CharField(choices=[('line', 'Line (Wall)'), ('area', 'Area (Floor / Roof / Sheathing)'), ('count', 'Count (Posts / Hardware)'), ('opening', 'Opening (Window / Door)')], max_length=20),
        ),
    ]
