# Generated by Django 6.0.3 on 2026-07-04 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_toolpreset_tool_type_alter_trace_tool_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpreset',
            name='color',
            field=models.CharField(blank=True, help_text='Optional display color in #RRGGBB format.', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a color as a six-digit hex value, e.g. #0d6efd.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='trace',
            name='color',
            field=models.CharField(blank=True, help_text='Optional display color in #RRGGBB format.', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a color as a six-digit hex value, e.g. #0d6efd.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='toolpreset',
            name='tool_type',
            field=models.CharField(choices=[('line', 'Line (Wall)'), ('polyline', 'Polyline / Polygon'), ('area', 'Area (Floor / Roof / Sheathing)'), ('count', 'Count (Posts / Hardware)'), ('opening', 'Opening (Window / Door)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trace',
            name='tool_type',
            field=models.CharField(choices=[('line', 'Line (Wall)'), ('polyline', 'Polyline / Polygon'), ('area', 'Area (Floor / Roof / Sheathing)'), ('count', 'Count (Posts / Hardware)'), ('opening', 'Opening (Window / Door)')], max_length=20),
        ),
    ]
