# Generated by Django 6.0.3 on 2026-07-04 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_toolpreset_color_trace_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='parent_wall',
            field=models.ForeignKey(blank=True, help_text='For opening traces: the wall this window/door is cut into.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_openings', to='plans.trace'),
        ),
    ]
