# Generated by Django 6.0.3 on 2026-07-08 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimating', '0020_seed_default_assemblies'),
        ('plans', '0006_backfill_opening_parent_wall'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolpreset',
            options={'ordering': ['-is_favorite', 'name']},
        ),
        migrations.AddField(
            model_name='toolpreset',
            name='assembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_presets', to='estimating.assembly'),
        ),
        migrations.AddField(
            model_name='toolpreset',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
