# Generated by Django 6.0.3 on 2026-07-09 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimating', '0022_loadtype_lineitem_load_type_and_more'),
        ('plans', '0007_alter_toolpreset_options_toolpreset_assembly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpreset',
            name='load_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_presets', to='estimating.loadtype'),
        ),
        migrations.AddField(
            model_name='trace',
            name='load_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces', to='estimating.loadtype'),
        ),
    ]
