# Generated by Django 6.0.3 on 2026-07-08 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_alter_toolpreset_options_toolpreset_assembly_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolpreset',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='toolpreset',
            name='assembly',
        ),
        migrations.RemoveField(
            model_name='toolpreset',
            name='is_favorite',
        ),
    ]
