# Generated by Django 6.0.3 on 2026-07-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='category_order',
            field=models.JSONField(blank=True, default=list, help_text='Preferred material-list construction-system group order (list of estimating.Assembly.Category keys). Empty means "use the doc default order."'),
        ),
        migrations.AddField(
            model_name='account',
            name='item_order',
            field=models.JSONField(blank=True, default=dict, help_text='Preferred item order within each material-list group: {category_key: [role_string, ...]}. A role missing from its list sorts last.'),
        ),
    ]
