# Generated by Django 6.0.3 on 2026-07-03 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('nominal_dimension', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sale_unit', models.CharField(choices=[('each', 'Each'), ('linear_ft', 'Linear ft'), ('board_ft', 'Board ft'), ('box', 'Box'), ('roll', 'Roll'), ('sheet', 'Sheet')], default='each', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_ft', models.PositiveSmallIntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lengths', to='catalog.materialproduct')),
            ],
            options={
                'ordering': ['product', 'length_ft'],
                'constraints': [models.UniqueConstraint(fields=('product', 'length_ft'), name='unique_product_length'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('product',), name='unique_default_length_per_product')],
            },
        ),
    ]
