# Generated by Django 6.0.3 on 2026-07-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_seed_house_framing_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiallength',
            name='length_ft',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
