# Generated by Django 6.0.3 on 2026-07-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_seed_precut_stud_lengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialproduct',
            name='category',
            field=models.CharField(choices=[('dimensional', 'Dimensional Lumber'), ('pressure_treated', 'Pressure-Treated'), ('studs', 'Studs & Precut'), ('boards', 'Boards & Trim'), ('engineered', 'Engineered Lumber'), ('sheathing', 'Sheathing & Panels'), ('subfloor', 'Subfloor & Underlayment'), ('roofing', 'Roofing'), ('weather_barrier', 'Housewrap & Weather Barrier'), ('connectors', 'Connectors & Hardware'), ('fasteners', 'Fasteners & Adhesive'), ('decking', 'Decking & Railing'), ('concrete_misc', 'Concrete & Miscellaneous'), ('uncategorized', 'Uncategorized')], default='uncategorized', help_text='Catalog grouping used to organize the material library.', max_length=30),
        ),
    ]
