# Generated by Django 6.0.3 on 2026-07-07 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_layout_preferences'),
        ('catalog', '0013_alter_materialproduct_quantity_per_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per ordering unit: per stock piece for feet materials, per box for box materials, per each otherwise.', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_prices', to='accounts.account')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.materialproduct')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'material'), name='unique_price_per_account_material')],
            },
        ),
    ]
